services:
  studiumsplaner:
    image: ghcr.io/nicolasasauer/studiplan:latest
    container_name: studiplan
    ports:
      - "3000:3000"
    
    environment:
      NODE_ENV: production
    
    volumes:
      - studiplan_data:/data
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  studiplan_data:
