import 'dart:convert';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:studi_plan/models/lecture.dart';
import 'package:studi_plan/models/study_plan.dart';
import 'package:studi_plan/providers/study_plan_provider.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('StudyPlanProvider local mode', () {
    test('creates, protects and restores local users without a server', () async {
      SharedPreferences.setMockInitialValues({});
      final provider = StudyPlanProvider();

      await provider.initialize();
      await provider.enterLocalMode();

      expect(provider.localMode, isTrue);
      expect(provider.isLoggedIn, isFalse);

      final createResult = await provider.createUser('Alice', 'secret');
      expect(createResult, isNull);
      expect(provider.currentUser, 'Alice');

      await provider.initializePlan('Alice Plan', 6, 'winter');
      await provider.logout();

      expect(await provider.login('Alice', null), 'REQUIRES_PASSWORD');
      expect(await provider.login('Alice', 'secret'), isNull);
      expect(provider.currentUser, 'Alice');
      expect(provider.plan.planName, 'Alice Plan');

      provider.dispose();
    });

    test('keeps the selected local mode after logout', () async {
      SharedPreferences.setMockInitialValues({});
      final provider = StudyPlanProvider();

      await provider.initialize();
      await provider.enterLocalMode();
      await provider.createUser('Bob', null);

      await provider.logout();

      expect(provider.localMode, isTrue);
      expect(provider.isLoggedIn, isFalse);

      final restartedProvider = StudyPlanProvider();
      await restartedProvider.initialize();

      expect(restartedProvider.localMode, isTrue);
      expect(restartedProvider.isLoggedIn, isFalse);

      restartedProvider.dispose();
      provider.dispose();
    });

    test('restores a local plan after app restart and local re-login', () async {
      SharedPreferences.setMockInitialValues({});
      final provider = StudyPlanProvider();

      await provider.initialize();
      await provider.enterLocalMode();
      await provider.createUser('Clara', 'pw');
      await provider.initializePlan('Clara Plan', 8, 'summer');
      await provider.updateGradeWeighting(true);
      await provider.logout();
      provider.dispose();

      final restartedProvider = StudyPlanProvider();
      await restartedProvider.initialize();

      expect(restartedProvider.localMode, isTrue);
      expect(restartedProvider.isLoggedIn, isFalse);
      expect(await restartedProvider.login('Clara', 'pw'), isNull);
      expect(restartedProvider.plan.planName, 'Clara Plan');
      expect(restartedProvider.plan.regularSemesters, 8);
      expect(restartedProvider.plan.startSeason, 'summer');
      expect(restartedProvider.plan.weightAverageGradeByEcts, isTrue);

      restartedProvider.dispose();
    });

    test('migrates a legacy local plan to the first real local user', () async {
      final legacyPlan = StudyPlan(
        planName: 'Alter Offline-Plan',
        regularSemesters: 7,
        startSeason: 'summer',
        isConfigured: true,
      );

      SharedPreferences.setMockInitialValues({
        'sp_local_mode': true,
        'sp_plan': jsonEncode(legacyPlan.toJson()),
      });

      final provider = StudyPlanProvider();
      await provider.initialize();

      expect(provider.localMode, isTrue);
      expect(provider.isLoggedIn, isFalse);
      expect(await provider.getUsers(), isEmpty);

      expect(await provider.createUser('Alice', null), isNull);
      expect(provider.currentUser, 'Alice');
      expect(provider.plan.planName, 'Alter Offline-Plan');
      expect(await provider.getUsers(), ['Alice']);

      provider.dispose();
    });

    test('re-homes the old autogenerated lokal user to a real local account', () async {
      final legacyPlan = StudyPlan(
        planName: 'Lokaler Altbestand',
        regularSemesters: 6,
        startSeason: 'winter',
        isConfigured: true,
      );

      SharedPreferences.setMockInitialValues({
        'sp_local_mode': true,
        'sp_user': 'lokal',
        'sp_token': 'local-session:lokal',
        'sp_local_users': '[{"username":"lokal","passwordHash":null}]',
        'sp_plan_local_bG9rYWw=': jsonEncode(legacyPlan.toJson()),
      });

      final provider = StudyPlanProvider();
      await provider.initialize();

      expect(provider.localMode, isTrue);
      expect(provider.isLoggedIn, isFalse);
      expect(await provider.getUsers(), isEmpty);

      expect(await provider.createUser('Mia', null), isNull);
      expect(provider.currentUser, 'Mia');
      expect(provider.plan.planName, 'Lokaler Altbestand');

      provider.dispose();
    });

    test('updates a lecture even when it is moved to another semester', () async {
      SharedPreferences.setMockInitialValues({});
      final provider = StudyPlanProvider();

      await provider.initialize();
      await provider.enterLocalMode();
      await provider.createUser('Dana', null);
      await provider.initializePlan('Dana Plan', 2, 'winter');

      final original = Lecture(
        id: 'l1',
        name: 'Mathe',
        ects: 5,
        season: 'winter',
        color: '#FF6B6B',
        semesterId: 'semester-1',
      );
      await provider.addLecture(original, 'semester-1');

      await provider.updateLecture(
        original.copyWith(
          name: 'Mathe II',
          semesterId: 'semester-2',
          passed: true,
        ),
      );

      final firstSemester = provider.plan.semesters.firstWhere(
        (semester) => semester.id == 'semester-1',
      );
      final secondSemester = provider.plan.semesters.firstWhere(
        (semester) => semester.id == 'semester-2',
      );

      expect(firstSemester.lectures, isEmpty);
      expect(secondSemester.lectures, hasLength(1));
      expect(secondSemester.lectures.first.name, 'Mathe II');
      expect(secondSemester.lectures.first.passed, isTrue);

      provider.dispose();
    });

    test('can toggle a legacy semester lecture by id even without semester hint', () async {
      SharedPreferences.setMockInitialValues({});
      final provider = StudyPlanProvider();

      await provider.initialize();
      await provider.enterLocalMode();
      await provider.createUser('Elli', null);

      final err = await provider.importJson(jsonEncode({
        'planName': 'Legacy',
        'regularSemesters': 1,
        'startSeason': 'winter',
        'isConfigured': true,
        'semesters': [
          {
            'id': 'semester-1',
            'number': 1,
            'season': 'winter',
            'lectures': [
              {
                'id': 'l1',
                'name': 'Physik',
                'ects': 6,
                'season': 'winter',
                'color': '#45B7D1',
              },
            ],
          },
        ],
        'parkingLot': [],
      }));

      expect(err, isNull);
      expect(provider.plan.semesters.first.lectures.first.semesterId, 'semester-1');

      await provider.toggleLecturePassed('l1', null);

      expect(provider.plan.semesters.first.lectures.first.passed, isTrue);

      provider.dispose();
    });

    test('removes the old autogenerated lokal user when real users exist', () async {
      final generatedPlan = StudyPlan(
        planName: 'Generated',
        regularSemesters: 6,
        startSeason: 'winter',
        isConfigured: true,
      );

      SharedPreferences.setMockInitialValues({
        'sp_local_mode': true,
        'sp_user': 'lokal',
        'sp_token': 'local-session:lokal',
        'sp_local_users':
            '[{"username":"lokal","passwordHash":null},{"username":"Nico","passwordHash":null}]',
        'sp_plan_local_bG9rYWw=': jsonEncode(generatedPlan.toJson()),
      });

      final provider = StudyPlanProvider();
      await provider.initialize();
      final prefs = await SharedPreferences.getInstance();

      expect(provider.localMode, isTrue);
      expect(provider.isLoggedIn, isFalse);
      expect(await provider.getUsers(), ['Nico']);
      expect(prefs.getString('sp_plan_local_bG9rYWw='), isNull);

      provider.dispose();
    });
  });
}
